{% set name = "xtensor-python" %}
{% set version = "0.1.0" %}
# {% set sha256 = "025709893b89229f7723fd5c36faaaf8155c2d6558d63c2c51e9de1904f01c42" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    git_url: ../
    # fn: {{ name }}-{{ version }}.tar.gz
    # url: https://github.com/QuantStack/xtensor-python/archive/{{ version }}.tar.gz
    # sha256: {{ sha256 }}

build:
  number: 0

requirements:
  run:
    - xtensor
    - pybind11

test:
  commands:
    - test -d ${PREFIX}/include/xtensor-python  # [unix]
    - test -f ${PREFIX}/include/xtensor-python/pytensor.hpp  # [unix]
    - if exist %LIBRARY_INC%\xtensor-python\pytensor.hpp (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xtensor-python
  license: BSD
  license_file: LICENSE
  summary: 'Python bindings for xtensor, the C++ tensor algebra library'
  description: 'Multi dimensional arrays with broadcasting and lazy computing'
  doc_url: http://xtensor.readthedocs.io
  dev_url: https://github.com/QuantStack/xtensor

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jmabille
